src/Entity/File.php
<?php

namespace App\Entity;

use App\Repository\FileRepository;
use App\Trait\FileTrait;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FileRepository::class)]
class File
{

    use FileTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $size = null;

    #[ORM\Column(length: 255)]
    private ?string $path = null;

    #[ORM\Column(length: 255)]
    private ?string $original_name = null;

    #[ORM\Column(length: 60)]
    private ?string $type = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'files')]
    private ?Transfer $transfer = null;

    private ?string $nice_name = null;
    private ?string $nice_size = null;
    private ?bool $is_previewable = false;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $mime_type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getNiceName(): ?string
    {
        $this->nice_name = $this->setNiceName();

        return $this->nice_name;
    }

    private function setNiceName(): ?string
    {
        if ($this->getName() === null) {
            return null;
        }

        return '<i class="fs-17 ' . $this->getFileTypeIcon($this->getType()) . '"></i>&nbsp;' . $this->getName();
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): static
    {
        $this->size = $size;

        return $this;
    }

    private function setNiceSize(): static
    {
        $this->nice_size = $this->formatSize($this->getSize());

        return $this;
    }

    public function getNiceSize(): string
    {
        $this->setNiceSize();

        return $this->nice_size;
    }

    public function getIsPreviewable(): bool
    {
        return $this->is_previewable = $this->canPreview($this->getType());
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): static
    {
        $this->path = $path;

        return $this;
    }

    public function getOriginalName(): ?string
    {
        return $this->original_name;
    }

    public function setOriginalName(string $original_name): static
    {
        $this->original_name = $original_name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getTransfer(): ?Transfer
    {
        return $this->transfer;
    }

    public function setTransfer(?Transfer $transfer): static
    {
        $this->transfer = $transfer;

        return $this;
    }

    public function getMimeType(): ?string
    {
        return $this->mime_type;
    }

    public function setMimeType(?string $mime_type): static
    {
        $this->mime_type = $mime_type;

        return $this;
    }
}

src/Entity/Transfer.php
<?php

namespace App\Entity;

use App\Repository\TransferRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TransferRepository::class)]
class Transfer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    /**
     * @var Collection<int, File>
     */
    #[ORM\OneToMany(targetEntity: File::class, mappedBy: 'transfer', cascade: ['persist', 'remove'])]
    private Collection $files;

    #[ORM\Column(length: 200, nullable: true)]
    private ?string $accessToken = null;

    #[ORM\Column(nullable: true)]
    private ?array $rules = null;

    #[ORM\ManyToOne(inversedBy: 'transfers')]
    private ?User $sender = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $message = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $expired_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $state = null;

    #[ORM\Column(nullable: true)]
    private ?array $recepients = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $emiter = null;

    public function __construct()
    {
        $this->files = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, File>
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): static
    {
        if (!$this->files->contains($file)) {
            $this->files->add($file);
            $file->setTransfer($this);
        }

        return $this;
    }

    public function removeFile(File $file): static
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getTransfer() === $this) {
                $file->setTransfer(null);
            }
        }

        return $this;
    }

    public function getAccessToken(): ?string
    {
        return $this->accessToken;
    }

    public function setAccessToken(?string $accessToken): static
    {
        $this->accessToken = $accessToken;

        return $this;
    }

    public function getRules(): ?array
    {
        return $this->rules;
    }

    public function setRules(?array $rules): static
    {
        $this->rules = $rules;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): static
    {
        $this->sender = $sender;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function getExpiredAt(): ?\DateTimeImmutable
    {
        return $this->expired_at;
    }

    public function setExpiredAt(?\DateTimeImmutable $expired_at): static
    {
        $this->expired_at = $expired_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(?string $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getRecepients(): ?array
    {
        return $this->recepients;
    }

    public function setRecepients(?array $recepients): static
    {
        $this->recepients = $recepients;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getEmiter(): ?string
    {
        return $this->emiter;
    }

    public function setEmiter(?string $emiter): static
    {
        $this->emiter = $emiter;

        return $this;
    }

    public function isExpired(): bool
    {
        return new DateTimeImmutable > $this->getExpiredAt();
    }
}

src/Form/TransferType.php
<?php

namespace App\Form;

use App\Entity\Transfer;
use App\Entity\User;
use App\Service\File\UploadFile;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class TransferType extends AbstractType
{
    public function __construct(
        private Security $security,
    ) {}

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Titre'])
            ->add('message')
            ->add('recepients', CollectionType::class, [
                'label' => 'Envoyer à',
                // each entry in the array will be an "email" field
                'entry_type' => EmailType::class,
                'delete_empty' => true,
                'allow_delete' => true,
                'allow_add' => true,
                'prototype' => true,
                // these options are passed to each "email" type
                'entry_options' => [
                    'attr' => ['class' => 'email-box'],
                    'label' => false
                ],
            ])
            ->add('file', FileType::class, [
                'label' => 'Fichiers',
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '512m',
                        'mimeTypes' => [
                            ...UploadFile::ARCHIVE_MIMES,
                            ...UploadFile::AUDIO_MIMES,
                            ...UploadFile::CODE_MIMES,
                            ...UploadFile::IMAGE_MIMES,
                            ...UploadFile::PDF_MIMES,
                            ...UploadFile::PRESENTATION_MIMES,
                            ...UploadFile::TABLEUR_MIMES,
                            ...UploadFile::TEXTE_MIMES,
                            ...UploadFile::TRAITEMENT_DE_TEXTE_MIMES,
                            ...UploadFile::VIDEO_MIMES,
                        ],
                        'mimeTypesMessage' => 'Please upload a valid PDF document',
                    ])
                ],
            ])
            ->add('emiter', TextType::class, [
                'label' => 'Votre adresse e-mail',
                'data' => $this->getUserEmail() ?? '',
                'row_attr' => [
                    'class' => $this->getUser() instanceof User ? 'd-none' : '',
                ],
                'attr' => [
                    'disabled' => $this->getUser() instanceof User,
                ]
            ])
            ->add('save', SubmitType::class, ['label' => 'Transférer'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Transfer::class,
        ]);
    }

    private function getUserEmail(): ?string
    {
        if ($this->getUser() instanceof User) {
            return $this->getUser()->getEmail();
        }

        return null;
    }

    /**
     * @return User|null
     */
    private function getUser(): ?User
    {
        $user = $this->security->getUser();

        return $user instanceof User ? $user : null;
    }
}

src/Controller/TransferController.php
<?php

namespace App\Controller;

use App\Entity\File;
use App\Repository\TransferRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\File as DownloadedFile;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/transfer', name: 'app_transfer_')]
final class TransferController extends AbstractController
{

    public function __construct(private TransferRepository $transferRepository) {}


    #[Route('/{accessToken}', name: 'show', methods: ['GET'])]
    public function show(string $accessToken): Response
    {
        $transfer = $this->transferRepository->findOneBy(compact('accessToken'));

        return $this->render('transfer/show.html.twig', compact('transfer'));
    }

    #[Route('/file/download/{id}', name: 'file_download', methods: ['GET'], requirements: ['id' => '\d+'])]
    public function download(File $file): Response
    {
        $dowmloadedFile = new DownloadedFile($file->getPath());

        return $this->file($dowmloadedFile, $file->getOriginalName(), ResponseHeaderBag::DISPOSITION_ATTACHMENT);
    }
}

templates/transfer/show.html.twig
{% extends "layouts/app.html.twig" %}

{% block content %}
  <section class="section container-fluid container-xxl" style="min-height: 66vh;">
    {% if transfer == null %}
      <!-- Warning Alert -->
      <div class="alert alert-warning alert-additional shadow fade show mb-0" role="alert">
        <div class="alert-body">
          <div class="d-flex">
            <div class="flex-shrink-0 me-3">
              <i class="ri-alert-line fs-16 align-middle"></i>
            </div>
            <div class="flex-grow-1">
              <h5 class="alert-heading">Ooops</h5>
              <p class="mb-0">Ce lien semble éronné.</p>
            </div>
          </div>
        </div>
        <div class="alert-content">
          <p class="mb-0">Veuillez contacter la personne qui vous a envoyée ce transfer.</p>
        </div>
      </div>
    {% endif %} 
    {% if transfer.isExpired() %}
      <!-- Warning Alert -->
      <div class="alert alert-warning alert-additional shadow fade show mb-0" role="alert">
        <div class="alert-body">
          <div class="d-flex">
            <div class="flex-shrink-0 me-3">
              <i class="ri-alert-line fs-16 align-middle"></i>
            </div>
            <div class="flex-grow-1">
              <h5 class="alert-heading">Ooops</h5>
              <p class="mb-0">Ce lien que vous avez utilisé a expiré.</p>
            </div>
          </div>
        </div>
        <div class="alert-content">
          <p class="mb-0">Veuillez contacter la personne qui vous a envoyée ce transfer.</p>
        </div>
      </div>
    {% else %}
      <div class="row align-items-center mb-2">
        <h1 class="h2 col-auto">
          {{ transfer.name }}
        </h1>
        <span class="ms-3 col-auto d-inline-block badge bg-primary-subtle text-primary fs-12">Expire le {{ transfer.expiredAt|date('d-m-Y') }}</span>
      </div>
      <div class="row">
        {% if transfer.message %}
          <div class="w-100 bg-light mb-4 rounded p-3">
            {{ transfer.message|capitalize }}
          </div>
        {% endif %}
      </div> 

      <div class="table-responsive table-card">
        <table class="table table-nowrap table-striped-columns my-2">
          <thead class="table-light">
              <tr>
                  <th scope="col">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" id="selectAllFiles">
                      <label class="form-check-label" for="selectAllFiles"></label>
                    </div>
                  </th>
                  <th scope="col">Nom du fichier</th>
                  <th scope="col">Taille</th>
                  <th scope="col">Actions</th>   
              </tr>
          </thead>
          <tbody>
            {% for file in transfer.files %}
              <tr>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="cardtableCheck01">
                        <label class="form-check-label" for="cardtableCheck01"></label>
                    </div>
                </td>
                <td> {{ file|file_widget }} </td>
                <td> {{ file.niceSize }} </td>
                <td>
                  {% if file.isPreviewable %}
                    <button 
                      onclick="preview(event);" 
                      data-file-type="{{ skip_accent(file.type)|lower }}" 
                      data-file-path="{{ file.path }}" 
                      data-file-original-name="{{ file.originalName }}"
                      data-file-mime-type="{{ file.mimeType }}"
                      type="button" 
                      class="btn btn-ghost-primary btn-icon" 
                      data-bs-toggle="modal" 
                      data-bs-target="#previewModal"
                      title="Visualiser le fichier"
                    ><i class="fs-13 ri-external-link-line"></i></button>
                  {% endif %}
                  <a href="{{ path('app_transfer_file_download', {id: file.id}) }}" class="btn btn-ghost-secondary btn-icon" title="Télécharger le fichier"><i class="fs-13 ri-download-2-line"></i></a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% endif %}
  </section>
  <div id="previewModal" class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="previewModalLabel" aria-modal="true" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div id="mediaContainer">
            </div>
          </div>
          <div class="modal-footer justify-content-center">
            <button type="button" class="btn btn-ghost-danger" data-bs-dismiss="modal">
              <i class="ri-close-line me-1 align-middle"></i>
              Fermer
            </button>
          </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div>
{% endblock %}

{% block js %}

<script src="{{ asset('/js/transfer.js') }}"></script>

{% endblock %}